### ISSUE TITLE
ImportError: cannot import name 'final' from 'typing' (/usr/local/lib/python3.7/typing.py)

### ISSUE THREAD

**Issue by basicvisual** [facebookresearch/d2go#60]
Hi I was trying to run D2go on google collab . Following were my steps

- Install Conda in google collab 
```
# Install conda and add channels to look for packages in
import sys
! wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
! chmod +x Anaconda3-2020.02-Linux-x86_64.sh
! bash ./Anaconda3-2020.02-Linux-x86_64.sh -b -f -p /usr/local
sys.path.append('/usr/local/lib/python3.7/site-packages/')
! conda update -n base -c defaults conda -y
! conda config --add channels bioconda
! conda config --add channels conda-forge
```

- Install the rest of dependencies in step 
```
!conda install pytorch torchvision cudatoolkit=11.0 -c pytorch
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
!python -m pip install 'git+https://github.com/facebookresearch/mobile-vision.git'
!git clone https://github.com/facebookresearch/d2go
%cd d2go 
!python -m pip install .
#install the pyyaml verision
!pip install pyyaml
!wget http://images.cocodataset.org/val2017/000000439715.jpg -q -O input.jpg
#run demo
!python demo.py --config-file faster_rcnn_fbnetv3a_C4.yaml --input /content/d2go/demo/input.jpg --output output1.jpg 

I get the following error 
I was wondering what  changes are  needed to be done ?
```
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    from d2go.model_zoo import model_zoo
  File "/usr/local/lib/python3.7/site-packages/d2go/model_zoo/model_zoo.py", line 8, in <module>
    from d2go.runner import create_runner
  File "/usr/local/lib/python3.7/site-packages/d2go/runner/__init__.py", line 10, in <module>
    from .default_runner import BaseRunner, Detectron2GoRunner, GeneralizedRCNNRunner
  File "/usr/local/lib/python3.7/site-packages/d2go/runner/default_runner.py", line 31, in <module>
    from d2go.export.caffe2_model_helper import update_cfg_from_pb_model
  File "/usr/local/lib/python3.7/site-packages/d2go/export/__init__.py", line 5, in <module>
    from . import caffe2  # noqa
  File "/usr/local/lib/python3.7/site-packages/d2go/export/caffe2.py", line 10, in <module>
    from d2go.export.api import ModelExportMethodRegistry, ModelExportMethod
  File "/usr/local/lib/python3.7/site-packages/d2go/export/api.py", line 32, in <module>
    from typing import final
ImportError: cannot import name 'final' from 'typing' (/usr/local/lib/python3.7/typing.py)
```



```

**Comment by sadegh16** [comment]
I have the same issue. Have you tested with a more recent version of python? (e.g. 3.8)

**Comment by basicvisual** [comment]
Hi , I have not .I think in google collab the default python version is 3.7

**Comment by gedance** [comment]
Oops! I got the latest D2Go, and now I am getting this error too.

**Comment by basicvisual** [comment]
Hi yes , i tried different configurations and changed the python version as well but i still get the error.  I was wondering if anyone else has the error

**Comment by RajkumarGalaxy** [comment]
Hi all. I too had this error. It is because D2Go expects python 3.8. Google Colab has Python 3.7 by default. In Python 3.7, there is no method `final` in the `typing` module - but Python 3.8 has one.
**Solution:** (this may not be the legal way, but solved my issue)
I thought that `final` method is not really important in D2Go. Hence, in Colab, go to Files (present on your left side margin).
go to /content/d2go/d2go/export/api.py
double-click on api.py
it opens python file on your right side
comment the line as below

`#from typing import final`

and, in the class `ModelExportMethod`,

`#@final`

That's it. Save the file. Close it. 
Run your codes as usual.

Hope it helps!

**Comment by basicvisual** [comment]
@RajkumarGalaxy can i ask you how have you installed the whole module without conda on google colab?

**Comment by RajkumarGalaxy** [comment]
Hi @basicvisual. I got the same error and I could not go further (in both GPU and CPU runtimes), as like you. I searched a lot but I could not find a module named `torch` in mobile_cv.

One of the contributors suggested this notebook (without conda):
[https://colab.research.google.com/gist/zhanghang1989/4ab8cbecbd05e1cc8fca8fd4dbaf8841/d2go_beginner.ipynb
](https://colab.research.google.com/gist/zhanghang1989/4ab8cbecbd05e1cc8fca8fd4dbaf8841/d2go_beginner.ipynb
)

Please run this notebook with GPU runtime. I have not tried yet. Hope it may work for you!

**Comment by basicvisual** [comment]
Hi @RajkumarGalaxy , thanks for the link but unfortunately it fails to import the D2go module itself

**Comment by RajkumarGalaxy** [comment]
Hi @basicvisual, have you restarted the runtime after executing the first cell?

**Comment by RajkumarGalaxy** [comment]
When I run this cell:

`from d2go.model_zoo import model_zoo`
`model = model_zoo.get('faster_rcnn_fbnetv3a_C4.yaml', trained=True)`

I get this error:
![image](https://user-images.githubusercontent.com/59993678/116895239-9a3d4580-ac50-11eb-8722-8726e1203074.png)

**Comment by basicvisual** [comment]
yes exaxtly the same error

**Comment by smahesh2694** [comment]
@basicvisual you may override the `ModuleNotFoundError: No module named 'mobile_cv.torch'` error by
replacing the line https://github.com/facebookresearch/d2go/blob/e84d3414feaf122ffcb01dcd9d6decbc076cee64/d2go/export/logfiledb.py#L8 with from detectron2.export.shared import ScopedWS

Thanks to @petoor for the quick fix. Original answer here -> https://github.com/facebookresearch/d2go/issues/64#issue-875525685

**Comment by zhanghang1989** [comment]
> When I run this cell:
> 
> `from d2go.model_zoo import model_zoo`
> `model = model_zoo.get('faster_rcnn_fbnetv3a_C4.yaml', trained=True)`
> 
> I get this error:
> ![image](https://user-images.githubusercontent.com/59993678/116895239-9a3d4580-ac50-11eb-8722-8726e1203074.png)

@kazhang It seems lightning imports torchtext. Any ideas about this error?

**Comment by basicvisual** [comment]
Thanks @smahesh2694 , i did manage to overcome the ``cv2` ` error but it resulted in onnx error , although all the modules have been installed

**Comment by petoor** [comment]
facebooks internal unit tests are breaking : https://github.com/facebookresearch/d2go/runs/2507011667
It shouldnt take long (hopefully) before this issue is fixed

Regarding the onnx==1.8.1 (hopefully facebooks just makes d2go work with onnx==1.9.0)
This seems to be fixing the problem in my system as well (That is, i can export a model to caffe2 - I dont know your use case). However, when i load the model for inference i get the following:

`  File "d2go_predictor.py", line 19, in <module>
    model = create_predictor(predictor_path)
  File "/home/peter/anaconda3/lib/python3.8/site-packages/mobile_cv/predictor/api.py", line 135, in create_predictor
    return _create_predictor(
  File "/home/peter/anaconda3/lib/python3.8/site-packages/mobile_cv/predictor/api.py", line 145, in _create_predictor
    predictor_info = PredictorInfo.from_dict(info_dict)
  File "/home/peter/anaconda3/lib/python3.8/site-packages/mobile_cv/predictor/api.py", line 92, in from_dict
    if "model" in dic:
TypeError: __new__() got an unexpected keyword argument 'type'
`

Which im pretty sure is related to : https://github.com/facebookresearch/d2go/issues/56

**Comment by basicvisual** [comment]
@petoor thanks for the reply. I did maanage to run the demo on a input jpeg. I did the following change as I mentioned before. However I am having problems running the the `demo.py` with `--video-input` flag . ( In colab)
`!python demo.py --config-file keypoint_rcnn_fbnetv3a_dsmask_C4.yaml --video-input /content/d2go/video.mp4  
`  
It seems to give an error . Do you have any problems running on video input ?

**Comment by petoor** [comment]
I havn't tried, but whats the error?

**Comment by basicvisual** [comment]
This could be a bit strange but I am running in collab as I had mentioned before. I do get the video processed but i dont see the output file saved . Perhaps it is something very basic . The command used 
`!python demo.py --config-file keypoint_rcnn_fbnetv3a_dsmask_C4.yaml --video-input /content/d2go/sissela.mp4  --output test`
The console output is as follows 

```
usr/local/lib/python3.7/site-packages/d2go/utils/misc.py:42: UserWarning: Installed torch version 1.7.1 does not satisfy the minimum required version 1.7.2
  warnings.warn(msg)
[05/05 09:52:29 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='keypoint_rcnn_fbnetv3a_dsmask_C4.yaml', input=None, opts=[], output='test', video_input='/content/d2go/sissela.mp4', webcam=False)
Arguments ['width_divisor', 'dw_skip_bnrelu', 'zero_last_bn_gamma'] skipped for op Conv2d
[05/05 09:52:29 fvcore.common.checkpoint]: [Checkpointer] Loading from https://mobile-cv.s3-us-west-2.amazonaws.com/d2go/models/250430934/model_0389999.pth ...
[05/05 09:52:29 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
[ERROR:0] global /tmp/pip-req-build-7m_g9lbm/opencv/modules/videoio/src/cap.cpp (561) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.1) /tmp/pip-req-build-7m_g9lbm/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): test in function 'icvExtractPattern'


  0% 0/130 [00:00<?, ?it/s]/usr/local/lib/python3.7/site-packages/detectron2/modeling/roi_heads/fast_rcnn.py:154: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370156314/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  filter_inds = filter_mask.nonzero()
100% 130/130 [00:48<00:00,  2.67it/s]
```
But i didnt get the output video saved . It seems to process the images

**Comment by petoor** [comment]
Sorry, don't know that one but it seems to be unrelated to this issue.
I still think it is a d2go bug though.

**Comment by ajay01994** [comment]
same error , can anyone please look into it or has anyone been able to solve the issue

**Comment by zhanghang1989** [comment]
> Sorry, don't know that one but it seems to be unrelated to this issue.
> I still think it is a d2go bug though.

python 3.8 solves the issue of importing final

**Comment by CrappyGit** [comment]
try modifying line 32 in `/your/d2go/directory/export/api.py` to `from typing_extensions import final` if you're using python3.7 or below
